# Generated by Django 4.0.5 on 2022-06-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_task_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_dt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
