# Generated by Django 4.0.5 on 2022-07-02 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_task_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='task',
            name='slug',
            field=models.SlugField(default=datetime.time, max_length=250, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.TextField(verbose_name='Текст'),
        ),
    ]
