# Generated by Django 4.0.5 on 2022-07-02 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_alter_task_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='slug',
            field=models.SlugField(default=datetime.time, max_length=250, verbose_name='Ссылка'),
        ),
    ]
