# Generated by Django 4.0.5 on 2022-07-02 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_alter_task_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AlterField(
            model_name='task',
            name='slug',
            field=models.SlugField(default=datetime.datetime, max_length=250, verbose_name='Ссылка'),
        ),
    ]
