# Generated by Django 4.0.5 on 2022-07-02 11:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0013_task_publish_alter_task_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_dt',
        ),
        migrations.AlterField(
            model_name='task',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Публикация'),
        ),
    ]
